baseURL: http://example.org/                  # Hosting location.
languageCode: en-us                           # Locale
title: Acme Corporation                       # Name of the website
# theme: Eclectic                               # Name of the theme
# theme: acme                                   # Name of the theme
# theme: github.com/hugoinaction/Eclectic
theme: github.com/hugoinaction/Acme
publishDir: public                            # Output folder
enableEmoji: true                             # Enable Emoticons

Paginate: 3 # Number of posts that should be shown in a page using the `.Paginator` object